--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Homebrew)
-- Dumped by pg_dump version 14.17 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    is_enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT app_user_role_check CHECK (((role)::text = 'BASIC'::text))
);


ALTER TABLE public.app_user OWNER TO efeon;

--
-- Name: app_user_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

CREATE SEQUENCE public.app_user_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_user_seq OWNER TO efeon;

--
-- Name: application_timeline; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.application_timeline (
    id bigint NOT NULL,
    description text,
    event_time timestamp(6) without time zone NOT NULL,
    event_type character varying(255) NOT NULL,
    job_application_id bigint NOT NULL,
    CONSTRAINT application_timeline_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['CREATED'::character varying, 'UPDATED'::character varying, 'SUBMITTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.application_timeline OWNER TO efeon;

--
-- Name: application_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.application_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachment; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.attachment (
    id bigint NOT NULL,
    file_path character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    job_application_id bigint NOT NULL,
    CONSTRAINT attachment_type_check CHECK (((type)::text = ANY ((ARRAY['JOB_DESCRIPTION'::character varying, 'OFFER_LETTER'::character varying, 'INTERVIEW_PREP'::character varying, 'REJECTION_LETTER'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.attachment OWNER TO efeon;

--
-- Name: attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT audit_log_action_check CHECK (((action)::text = ANY ((ARRAY['CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[])))
);


ALTER TABLE public.audit_log OWNER TO efeon;

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communication_log; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.communication_log (
    id bigint NOT NULL,
    direction character varying(255) NOT NULL,
    message text,
    "timestamp" timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    job_application_id bigint NOT NULL,
    CONSTRAINT communication_log_direction_check CHECK (((direction)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying])::text[]))),
    CONSTRAINT communication_log_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL'::character varying, 'CALL'::character varying, 'LINKEDIN'::character varying, 'IN_PERSON'::character varying])::text[])))
);


ALTER TABLE public.communication_log OWNER TO efeon;

--
-- Name: communication_log_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.communication_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communication_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cover_letter; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.cover_letter (
    id bigint NOT NULL,
    content oid,
    file_path character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.cover_letter OWNER TO efeon;

--
-- Name: cover_letter_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.cover_letter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cover_letter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow_up_reminder; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.follow_up_reminder (
    id bigint NOT NULL,
    note text,
    remind_on timestamp(6) without time zone NOT NULL,
    job_application_id bigint NOT NULL
);


ALTER TABLE public.follow_up_reminder OWNER TO efeon;

--
-- Name: follow_up_reminder_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.follow_up_reminder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_up_reminder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_application; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.job_application (
    id bigint NOT NULL,
    applied_on timestamp(6) without time zone,
    company character varying(255) NOT NULL,
    job_title character varying(255) NOT NULL,
    notes text,
    status character varying(255) NOT NULL,
    cover_letter_id bigint,
    location_id bigint,
    resume_id bigint,
    source_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT job_application_status_check CHECK (((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'INTERVIEW'::character varying, 'OFFER'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.job_application OWNER TO efeon;

--
-- Name: job_application_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.job_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_source; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.job_source (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.job_source OWNER TO efeon;

--
-- Name: job_source_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.job_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL
);


ALTER TABLE public.location OWNER TO efeon;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.resume (
    id bigint NOT NULL,
    file_path character varying(255) NOT NULL
);


ALTER TABLE public.resume OWNER TO efeon;

--
-- Name: resume_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.resume ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_communication; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.scheduled_communication (
    id bigint NOT NULL,
    notes text,
    scheduled_for timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    job_application_id bigint NOT NULL,
    CONSTRAINT scheduled_communication_type_check CHECK (((type)::text = ANY ((ARRAY['INTERVIEW'::character varying, 'ONLINE_ASSESSMENT'::character varying, 'CALL'::character varying])::text[])))
);


ALTER TABLE public.scheduled_communication OWNER TO efeon;

--
-- Name: scheduled_communication_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.scheduled_communication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduled_communication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skill_tracker; Type: TABLE; Schema: public; Owner: efeon
--

CREATE TABLE public.skill_tracker (
    id bigint NOT NULL,
    skill_name character varying(255) NOT NULL,
    job_application_id bigint NOT NULL
);


ALTER TABLE public.skill_tracker OWNER TO efeon;

--
-- Name: skill_tracker_id_seq; Type: SEQUENCE; Schema: public; Owner: efeon
--

ALTER TABLE public.skill_tracker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_tracker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: application_timeline application_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.application_timeline
    ADD CONSTRAINT application_timeline_pkey PRIMARY KEY (id);


--
-- Name: attachment attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: communication_log communication_log_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.communication_log
    ADD CONSTRAINT communication_log_pkey PRIMARY KEY (id);


--
-- Name: cover_letter cover_letter_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.cover_letter
    ADD CONSTRAINT cover_letter_pkey PRIMARY KEY (id);


--
-- Name: follow_up_reminder follow_up_reminder_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.follow_up_reminder
    ADD CONSTRAINT follow_up_reminder_pkey PRIMARY KEY (id);


--
-- Name: job_application job_application_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT job_application_pkey PRIMARY KEY (id);


--
-- Name: job_source job_source_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_source
    ADD CONSTRAINT job_source_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: resume resume_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.resume
    ADD CONSTRAINT resume_pkey PRIMARY KEY (id);


--
-- Name: scheduled_communication scheduled_communication_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.scheduled_communication
    ADD CONSTRAINT scheduled_communication_pkey PRIMARY KEY (id);


--
-- Name: skill_tracker skill_tracker_pkey; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.skill_tracker
    ADD CONSTRAINT skill_tracker_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: job_source uk7di4ltcrh49tpjr94ecflc24r; Type: CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_source
    ADD CONSTRAINT uk7di4ltcrh49tpjr94ecflc24r UNIQUE (name);


--
-- Name: job_application fk3dc7sb9ywko943m7y0jjkq6u7; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fk3dc7sb9ywko943m7y0jjkq6u7 FOREIGN KEY (resume_id) REFERENCES public.resume(id);


--
-- Name: job_application fk3yffvmwtgv5fndmij3hyyfyuj; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fk3yffvmwtgv5fndmij3hyyfyuj FOREIGN KEY (location_id) REFERENCES public.location(id);


--
-- Name: application_timeline fk9a6j2ullqxpfgfyrod6v8ilvw; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.application_timeline
    ADD CONSTRAINT fk9a6j2ullqxpfgfyrod6v8ilvw FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: communication_log fkah8jwpfnrcdyu2eb17jqdhmc3; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.communication_log
    ADD CONSTRAINT fkah8jwpfnrcdyu2eb17jqdhmc3 FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: job_application fkc9lj9xkj8qfnmkut31jqek9pm; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkc9lj9xkj8qfnmkut31jqek9pm FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: job_application fkfmfpl94j9e3msjos28q11yqcu; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkfmfpl94j9e3msjos28q11yqcu FOREIGN KEY (source_id) REFERENCES public.job_source(id);


--
-- Name: skill_tracker fkg51oidtk61mcsqf1onj2gpa30; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.skill_tracker
    ADD CONSTRAINT fkg51oidtk61mcsqf1onj2gpa30 FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: attachment fkksmtcoja0o2t8a990ixqcsmrv; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkksmtcoja0o2t8a990ixqcsmrv FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: scheduled_communication fkqcqu8p93cnaxbwwrovojmoonb; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.scheduled_communication
    ADD CONSTRAINT fkqcqu8p93cnaxbwwrovojmoonb FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: follow_up_reminder fkqfls5a9nhse1g8ct1rnvactew; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.follow_up_reminder
    ADD CONSTRAINT fkqfls5a9nhse1g8ct1rnvactew FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: job_application fkql1meal13nvlac0fcjf22tmpe; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkql1meal13nvlac0fcjf22tmpe FOREIGN KEY (cover_letter_id) REFERENCES public.cover_letter(id);


--
-- Name: audit_log fkqsu5o6fffuhrg94lncceiey3n; Type: FK CONSTRAINT; Schema: public; Owner: efeon
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkqsu5o6fffuhrg94lncceiey3n FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- PostgreSQL database dump complete
--

