# .github/workflows/ci.yml
name: Java CI/CD with Gradle - Pro Version

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Grant permission to Gradle wrapper
      run: chmod +x gradlew

    - name: Build and run tests
      run: ./gradlew clean build --info

    - name: Archive Test Reports
      if: always()  # even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests/test

    - name: Archive Build Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: build/reports

  # Optional: add Deployment job here after tests pass!
